services:
  storage:
    image: minio/minio
    container_name: storage
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - ../minio-data:/data

  model-trainer:
    image: jupyter/scipy-notebook
    container_name: model-trainer
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/home/jovyan/work
      - ../data:/home/jovyan/data
    environment:
      - JUPYTER_TOKEN=admin
