services:
  storage:
    image: minio/minio
    container_name: storage
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - ../minio-data:/data

  minio-init:
    image: python:3.11-slim
    container_name: minio-init
    working_dir: /app
    volumes:
      - ../src:/app/src
    command: sh -c "pip install boto3 && python /app/src/init/init_minio.py"
    depends_on:
      - storage
      
  federated-learning:
    build:
      context: ..
      dockerfile: projects/federated-learning/Dockerfile
    container_name: federated-learning
    volumes:
      - ../projects/federated-learning:/app
      - ../data:/app/data
    command: python -u /app/src/main.py
    depends_on:
      - storage
      - minio-init
  
  intrusion-detection-system:
    build:
      context: ..
      dockerfile: projects/intrusion-detection-system/Dockerfile
    container_name: intrusion-detection-system
    volumes:
      - ../projects/intrusion-detection-system:/app
      - ../data:/app/data
    command: python /app/src/main.py
    depends_on:
      - storage
      - minio-init

  bias-detection-and-mitigation:
    build:
      context: ..
      dockerfile: projects/bias-detection-and-mitigation/Dockerfile
    container_name: bias-detection-and-mitigation
    volumes:
      - ../projects/bias-detection-and-mitigation:/app
      - ../data:/app/data
    command: python /app/main.py
    depends_on:
      - storage
      - minio-init
  
